# We're converting configuration files to YAML for increased readability
# and the ability to include comments. Config files need comments.

tornado:
    address: 127.0.0.1
    port: 5000
    cookie_secret: 21a820a1d0f4b11b3c6f38b0e7849b7702b398a4

database:
    host: localhost
    db: wurkhappy
    user: www
    passwd: ""

smtp:
    user: contact@wurkhappy.com
    from: 'Wurk Happy'
    email: contact@wurkhappy.com
    password: 
    host: smtp.gmail.com
    port: 587

amazonaws:
    key_id: 
    key_secret: 
    bucket_name: media.wurkhappy.com
